
services:
  database:
    image: questdb/questdb:8.1.4
    ports:
      - 9003:9003
      - 9000:9000 
      - 8812:8812
    volumes:
      - ./database:/var/lib/questdb
  broker:
    image: emqx/nanomq:0.23
    environment:
      - NANOMQ_HTTP_SERVER_ENABLE=True
    ports:
      - 1883:1883 
      - 8081:8081
      - 8883:8883
